### PR TITLE
Last minute changes from the asguard robot

### PR DESCRIPTION
**Pull request by pierrewillenbrockdfki**
This commit was found on the asguard robot and actually fixes at least one bug.

### CODE REVIEW

**Comment by Rauldg** [comment]
@chhtz can this be merged?

**Comment by pierrewillenbrockdfki** [comment]
The mentioned bug is that skid4_control will segfault in the start_hook by running out of stack.

**Comment by chhtz** [comment]
I don't recall when/who did this. Removing the recursive call to itself obviously fixes an infinite recursion bug. Can't say much about the other changes.
Apparently, that was the version that has been running on the real system so it should be reasonably safe to merge it.

**Comment by pierrewillenbrockdfki** [comment]
@chhtz, i am not sure who all has write access here, but i think you do, and i don't. Otherwise, we'll have to go hunt someone that actually can merge this.

**Pull request merged**
